### ISSUE TITLE
getting "No Credentails were found in the store" on production app

### ISSUE THREAD

**Issue by Aaqibali279** [auth0/Auth0.swift#863] opened 2024-07-09 11:39 UTC
### Checklist

- [X] The issue can be reproduced in the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/Auth0.swift#readme), [Examples](https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/Auth0.swift/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/documentation/auth0) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

this issue is reported randomly by users on production

### Reproduction

this issue is reported randomly by users on production

### Auth0.swift version

2.7.2

### Platform

iOS

### Platform version(s)

17+

### Xcode version

xcode 15.3

### Package manager

Cocoapods

**Comment by desusai7** [comment] 2024-07-11 05:43
This is a duplicate of #863, closing this so that we can target all the discussions around this issue at a single point.

**Closed by desusai7** 2024-07-11 05:43 UTC
Labels: bug
