### ISSUE TITLE
Links not resolving after migration to 2.x.x

### ISSUE THREAD

**Issue by thomas-labben** [auth0/Auth0.swift#737] opened 2022-09-02 03:28 UTC
### Checklist

- [X] The issue can be reproduced in the [Auth0.swift sample app](https://github.com/auth0-samples/auth0-ios-swift-sample/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/Auth0.swift#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/Auth0.swift/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/Auth0.swift/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tags/c/sdks/5/swift) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have migrated my app from 1.36.0 to 2.3.1. I removed the `resumeAuth` call from my AppDelegate however when opening the link received, the app simply does nothing. No console logs are printed, my result callback is never fired and the app simply does nothing.

```
let auth0 = Auth0
            .webAuth(clientId: "Some Client", domain: "Some Domain")
            .scope("openid profile offline_access")
            .audience(Auth0Constant.auth0Audience)
            .parameters(Auth0Constant.auth0Parameters)
            .state(Auth0Constant.appUUID)
            .logging(enabled: true)
            .start { result in
            switch result {
            case .success(let credentials):
                        print("Success")
            case .failure(let error):
                        print("Error")
            }
        }
```

### Reproduction

1. Invoke Web Auth
2. Tap link received via SMS
3. App reopens 
4. Modal web view does not dismiss
5. Auth callback is not triggered

### Auth0.swift version

2.3.1

### Platform

iOS

### Platform version(s)

12.0

### Xcode version

13.5

### Package manager

SPM

**Comment by Widcket** [comment] 2022-09-02 03:33
Hi @thomas-labben, thanks for raising this.

In the reproduction steps you mention "Tap link received via SMS" and "Modal web view does not dismiss". This sounds like you're trying to perform Classic Universal Login based passwordless. That is, initiating the passwordless flow from the browser window, and then expecting the browser window to close once the SMS link is tapped. Is that correct?

This is not supported by Auth0.swift.

**Comment by thomas-labben** [comment] 2022-09-02 03:35
Yes this is correct @Widcket 

This was previously supported via `Auth0.resumeAuth(_:)`. Is there an alternative solution recommended here by Auth0?

**Comment by Widcket** [comment] 2022-09-02 03:37
Were you using `useLegacyAuthentication()` with Auth0.swift 1.x?

**Comment by thomas-labben** [comment] 2022-09-02 03:39
Can confirm that we were NOT using `useLegacyAuthentication()`. We were in-fact using the exact same code as above. The only difference here is that we've removed `resumeAuth` from our AppDelegate, which subsequently means that the auth0 is no longer handling the `openUrl` delegate method when receiving links prefixed with`PRODUCT_BUNDLE_IDENTIFIER`

**Comment by Widcket** [comment] 2022-09-02 04:33
If you were not using `useLegacyAuthentication()` then the SDK was using `ASWebAuthentication` under the hood. `ASWebAuthentication` never really needed `Auth0.resumeAuth(_:)`, because it automatically captures the callback URL. `Auth0.resumeAuth(_:)` was needed for `SFSafariViewController`, which is what the SDK used when `useLegacyAuthentication()` was called.

`useLegacyAuthentication()` was removed in Auth0.swift v2. However, since Auth0.swift v2 re-added support for `SFSafariViewController` (see https://github.com/auth0/Auth0.swift/blob/master/FAQ.md#1-how-can-i-disable-the-login-alert-box) it includes it's own resume method: `WebAuthentication.resume(with: url)`.

We never really supported Classic Universal Login based passwordless. It would not work if the user closed the app, or if iOS killed it once backgrounded, because the entire auth transaction was kept in memory.

**Comment by Widcket** [comment] 2022-09-02 04:34
Auth0.swift supports embedded passwordless: https://github.com/auth0/Auth0.swift#passwordless-login
It requires building your own UI, though.

**Comment by Widcket** [comment] 2022-09-12 00:15
@thomas-labben seems like the above answers your questions. I'll close this issue, please feel free to comment if you'd prefer to reopen.

**Closed by Widcket** 2022-09-12 00:15 UTC
Labels: waiting for customer

**Comment by hervenivon** [comment] 2022-11-07 21:21
> Auth0.swift supports embedded passwordless: https://github.com/auth0/Auth0.swift#passwordless-login It requires building your own UI, though.

For others who might stumble upon this link. The new correct one is: https://github.com/auth0/Auth0.swift/blob/master/EXAMPLES.md#passwordless-login
