### ISSUE TITLE
App switch to confirm 2FA breaks authentication flow

### ISSUE THREAD

**Issue by Ethan-VisualVocal** [auth0/Auth0.swift#362] opened 2020-03-11 18:04 UTC
### Description
Same as this issue for the react-native plugin: 
https://github.com/auth0/react-native-auth0/issues/256
Similar to this issue for the Android plugin: 
https://github.com/auth0/Auth0.Android/issues/290

Post login that requires MFA, the user switches to the Authenticator app to approve the request, but when we return to our app that’s using Auth0.swift, we see a **“Safari cannot open the page because the network connection was lost”** message in the auth flow’s view controller. Reloading has no effect and the cycle simply repeats if I try again.

### Reproduction

**One Device:**
- Open an Auth0 webAuth session against an IdP that requires confirmation from an application such as Microsoft Authenticator on the same device
- Respond to 2FA confirmation request, causing app switch away from Auth0-using app
- Return to Auth0-using app following switch

**OR w/ two devices:**
- On Device 1, open an Auth0 webAuth session against an IdP that requires confirmation from an application such as Microsoft Authenticator on ANOTHER device, Device 2
- Device 1: Login on to initiate 2FA/MFA confirmation request
- Device 1: Suspend Auth0-using app and switch to any other app.
- Device 2: Approve 2FA request.
- Device 1: Return to Auth0-using app.

### Environment

- **Version of this library used: 1.19.3**
- **Other relevant versions (language, server software, OS, browser): iOS 13.3.1**
- **Other modules/plugins/libraries that might be involved: Microsoft Authenticator 6.3.29**

**Comment by Widcket** [comment] 2020-03-11 19:35
Hi @Ethan-VisualVocal, can you please share a video showcasing the issue?

**Comment by xparabolax** [comment] 2020-03-20 02:23
I think this is the same issue as auth0/react-native-auth0/issues/256. The workaround for us was to use `UIApplication.shared.beginBackgroundTask`. Basic idea:

```
import Auth0
import Foundation

class LoginVC: UIViewController {

    var backgroundTask: UIBackgroundTaskIdentifier = .invalid

    func attemptLogin() {
            self.backgroundTask = UIApplication.shared.beginBackgroundTask {
                self.backgroundTask = .invalid
                UIApplication.shared.endBackgroundTask(self.backgroundTask)
            }

            Auth0.webAuth() /* ... */ .start {                 
                switch $0 {
                    case .failure(let error):
                        print("Error: \(error)")
                    case .success(let credentials):
                        print("Credentials here")
                }
                self.backgroundTask = .invalid
                UIApplication.shared.endBackgroundTask(self.backgroundTask)
            }
    }
}
```

**Comment by xparabolax** [comment] 2020-03-20 02:25
We had the same issue and worked around it by using `UIApplication.shared.beginBackgroundTask`.
 https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/extending_your_app_s_background_execution_time

**Comment by Widcket** [comment] 2020-03-20 14:06
Hey @xparabolax, with which identity provider did this happen to you? I tried to repro with a Microsoft account + the MS authenticator app (that uses a push notification), but was unsuccessful.

**Comment by xparabolax** [comment] 2020-03-20 21:01
Hi @Widcket we had this occurring with Google IDP (G Suite linked to Microsoft) + MS Authenticator app. But, this seems to be not occurring anymore. I'm not sure why.

**Comment by Widcket** [comment] 2020-03-30 02:22
![RPReplay_Final1585534407](https://user-images.githubusercontent.com/5055789/77869062-95b78980-7213-11ea-9d16-ec02b990b361.gif)

Test environment:
- iOS 13.4
- Auth0.swift 1.22.1
- MS Account
- MS Authenticator App

Will close this issue due not being able to reproduce. If this is still a problem for you, please reply with a video showcasing the issue.

**Closed by Widcket** 2020-03-30 02:22 UTC
Labels: waiting for customer
