### ISSUE TITLE
WatchOS: Crash on credentialsManager.credentials

### ISSUE THREAD

**Issue by JMCPH** [auth0/Auth0.swift#492] opened 2021-08-04 13:27 UTC
### Describe the problem

We are having multiple watchOS user reporting that our app crashes when they open it, and based on the stack trace it's located to the credentialsManager.credentials call, which calls the:
` #0	(null) in CredentialsManager.retrieveCredentials(withScope:minTTL:callback:) ()`

Unfortunately we haven't been able to figure out what is causing the crash, but it's mostly on Apple Watch Series 3 the crash happens. I have appended 

### What was the expected behavior?
No crash

### Reproduction
Unfortunately we haven't been able to reproduce the bug.

**Stacktrace**
<img width="1026" alt="Screenshot 2021-08-04 at 15 25 58" src="https://user-images.githubusercontent.com/5514628/128188960-886dbc0d-b681-485a-99f0-906e24cc3c62.png">

**Crashreport file**
[q4piiE8WOpx49mKmqymAC.xccrashpoint.zip](https://github.com/auth0/Auth0.swift/files/6931587/q4piiE8WOpx49mKmqymAC.xccrashpoint.zip)

### Environment

- **Version of `Auth0.swift` used: 1.35.0**
- **Version of iOS/macOS/tvOS/watchOS: WatchOS 6 + WatchOS 7**
- **Version of Xcode: Xcode 12.5.1**

**Comment by JMCPH** [comment] 2021-08-06 11:09
**UPDATE**
We have shipped a version to TestFlight where we do not call the `credentialsManager.credentials` and that one is not crashing. It's still only occurring on Apple Watch Series 3, but I think that's a coincidence.

@Widcket do you have an idea what could cause it?

**Comment by Widcket** [comment] 2021-08-07 02:49
Hi @JMCPH, those crashes can be caused by dangling pointers. The Credentials Manager does not make use of raw pointers, but it uses [SimpleKeychain](https://github.com/auth0/SimpleKeychain) under the hood, which is written in Objective-C. `retrieveCredentials` in particular, calls the `store` method, that in turn calls the `setData` [method](https://github.com/auth0/SimpleKeychain/blob/master/SimpleKeychain/A0SimpleKeychain.m#L137)  from SimpleKeychain.
Have you been able to reproduce it and debug it with zombie objects enabled? Please let us know your findings.

**Comment by JMCPH** [comment] 2021-08-09 07:28
Thank you for your quick reply, @Widcket. Unfortunately, we haven't been able to reproduce the crash ourself, but it's happening consistently for some specific users, even if they delete the app on both iPhone and watchOS. We have also tried to make TestFlight build, where we cleaned the keychain and deleted every data inside the keychain. That didn't help either. Do you have an idea of how we can try to reproduce this?

**Comment by Widcket** [comment] 2021-08-10 02:43
@JMCPH if you're not able to reproduce it, you could try using your own logic to store the credentials on the Keychain, instead of the Credentials Manager, and see if the issue persists.
I'm not sure how else we can help if the problem can't be reproduced, other than suggesting that you check that you're not swizzling system classes or adding categories that could cause this problem.

**Comment by Widcket** [comment] 2021-08-23 20:31
@JMCPH I'll be closing this for now, please ping me if you'd like to reopen.

**Closed by Widcket** 2021-08-23 20:31 UTC
Labels: waiting for customer
